### ISSUE TITLE
mvn databus-derive:clone-parse keeps errors in result files

### ISSUE THREAD

**Issue by kurzum** [dbpedia/databus-derive#5]
@Vehnem I tested standalone and it worked, well: 
```
wget http://dbpedia-mappings.tib.eu/release/mappings/mappingbased-literals/2019.08.01/mappingbased-literals_lang=el.ttl.bz2
bzcat mappingbased-literals_lang\=el.ttl.bz2 | rapper -i ntriples -O - - file -c
mvn scala:run -Dlauncher=parse -DaddArgs="mappingbased-literals_lang=el.ttl.bz2|-o|test.nt.bz2|-r|report.out.bz2"
bzcat test.nt.bz2 | rapper -i ntriples -O - - file -c
```

I am assuming, that this is due to poor file handling. 
Maven has a $builddirectory for building stuff. However, you wrote the tool to build in $targetdir
Regardless if this is the error, it has to be fixed. 
My suggestion is building everything in `target/databus/derive`:
```
target/databus/derive/download
target/databus/derive/tmp
target/databus/derive/.spark_local_dir
target/databus/derive/final
```
then in a last step **copy** `final` to targetDir in overwrite mode

Deleting:
1. at start delete `target/databus/derive/`, maybe keep download (just an optimisation, not urgent)
2. don't delete during or at the end. Just keep everything. There is `mvn clean` for deleting the build directory

**Comment by Vehnem** [comment]
For branch "dev" and -Dlauncher="flatRdfParser" it looks also right, will now check mvn databus-derive:clone-parse there

**Comment by Vehnem** [comment]
Also checked the maven goal on the "dev" branch and it works. So Errors are removed and Warnings stay for now.
